name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Dar permisos a mvnw
        run: chmod +x ./mvnw

      - name: Build con Maven
        run: ./mvnw clean package -DskipTests

      - name: Conectando con usuario
        run: echo "${{ secrets.EC2_USER }}" | head -c 40


      - name: Copiar JAR y restart-app.sh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH }}
          source: |
            target/*.jar
            deploy-and-restart.sh
          target: "~/app"


